sonar.projectKey=sem-refatorar
sonar.projectName=Sem Refatorar
sonar.projectVersion=1.0
sonar.language=ts
sonar.sources=src
sonar.exclusions=**/*.spec.ts, **/node_modules/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_37e11c85bf59698545aec61531388462430527a0
